---

- name: Configure horizon
  lineinfile: dest=/etc/openstack-dashboard/local_settings.py
              regexp=^OPENSTACK_HOST
              line="OPENSTACK_HOST = '{{ keystone_hostname }}'"
  notify:
    - Restart apache2
