---

- name: Install horizon application and dependencies
  apt: name="{{ item }}" state=present
  with_items:
    - apache2
    - memcached
    - libapache2-mod-wsgi
    - openstack-dashboard

- name: Remove Ubuntu theme
  apt: name="{{ item }}" state=absent purge=yes
  with_items:
    - openstack-dashboard-ubuntu-theme
